### ISSUE TITLE
System Admin pages are showing field variable names instead of readable names

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject_plus#1]
![brewery fibre path1](https://user-images.githubusercontent.com/2577966/33110187-3804be3e-cf9a-11e7-8e0f-c27bef8238da.png)

**Comment by rafaelqg** [comment]
The translation file: "/locales/en/common.inc"  has been fixed. Now the readable names are being displayed instead of the variable names.
![admin_translations](https://user-images.githubusercontent.com/19318978/35185739-136b8b1e-fdf0-11e7-97ef-0f8220078267.png)
