### ISSUE TITLE
style/default/header.php is incomplete

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject_plus#3]
Hi @rafaelqg 
I'm just going through the process of merging this into master as a clean/fully functional dotproject_plus repository -

I'm going through the diffs in my merge, and noticed that `style/default/header.php` seems to be incomplete - the last 10 lines:
```
$ tail -n 10 style/default/header.php
            }
            function closeAppMessage(){
                document.getElementById("app_message_panel").style.display="none";
            }
        </script>
        <!-- end message panel -->
        <table width="100%" cellspacing="0" cellpadding="4" border="0">
            <tr>
                <td valign="top" align="left" width="98%">

```
There's a whole lot of close tags that seem to be missing (row, table, body, html) - can you have a look at it please?

**Comment by rafaelqg** [comment]
HI Bernard!

![footer](https://user-images.githubusercontent.com/19318978/35652843-9889897e-06cc-11e8-8010-440d4f8d933e.png)

Actually it isn't a bug. The closing of these tags is on footer.php file in the same directory.
It was not my choice, but looks like all dotproject themes (styles) have this structure.

**Comment by cleary** [comment]
Aha that all makes sense - thanks for having a look :)
